### ISSUE TITLE
Bot does not go online after typing in the secret

### ISSUE THREAD

**Issue by 0xAB51NTH** [hackermondev/discord-active-developer#1]
Hi, I have decided to test it in order to claim the badge but after i put the token from the copied replit it does nothing after that. The done message does not appear nor the bot goes online. Inputing invalid token key triggers nothing too.

**Comment by Snowman1221** [comment]
I also have this issue

**Comment by hackermondev** [comment]
@0xAB51NTH @Snowman1221 its probably a ratelimit issue, try again now and see if it still happens

**Comment by hackermondev** [comment]
https://github.com/hackermondev/discord-active-developer/commit/9377ea5626317caa0a4a18caa64850cfb26f18bd should fix this.
